name: estimagic-rtd

channels:

  - janosg
  - conda-forge
  - defaults

dependencies:

  - python=3.7
  - estimagic
  - sphinx=2.2.1
  - nbsphinx=0.4.3
  - sphinx_rtd_theme=0.4.3
  - sphinxcontrib-bibtex=1.0.0
  - jupyter=1.0.0
  - patsy=0.5.1
